### ISSUE TITLE
Tests fail in Julia 1.0

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/LoadFlint.jl#16]
CI tests recently started to fail with Julia 1.0 because the CI tests end up installing FLINT_jll v2.6.999+0, even though we yanked that version.

My suspicion is that "yanking a version" is not supported in the Pkg.jl bundled with 1.0.

So before we release an update of LoadFlint.j for the new FLINT_jll 200.690, perhaps we should release a minor update of the current version that restricts the version range. This may not be necessary if we are quick in releasing "all" packages using the new FLINT really soon -- but how likely is that...

**Comment by thofma** [comment]
This is not necessary. I already fixed the compat entries in the registry here: https://github.com/JuliaRegistries/General/pull/25388

We just need to bump the FLINT_jll version of the master branch here. I am currently producing the build_tarball.jl stuff for the 200.690 release (after adjusting build_tarball.jl) on julia 1.0.
